파일 업로드 기능 구현
zzuda/zuda-backend pull request #11
Opened 2021-05-02 09:11 UTC by HARDTACK-Dev

### 파일 업로드 기능을 구현하였습니다

---

 #### **📦생성된 목록**
> **[ 📁 ] file 폴더 생성**
> [+] file.controller.ts
> [+] file.service.ts 
> [+] file.module.ts

#### **파일저장용**
> [📁] **fileStorage**
> &nbsp; ㄴ temp
> &nbsp; ㄴ roomID

#### **기타**
> [🧱] **DTO** / upload-file-body.dto.ts
> [⚡] **ERRORS** / file.error.ts 

<br>

### 사항 

**`file.controller`에 파일 업로드 기능을 구현하였습니다.**
 접근 경로는 `localhost:8080/file/` 입니다
- file/upload를 이용하여 파일을 업로드 합니다
- file/delete를 이용하여 선택된 파일을 지웁니다
- file/deleteStorage를 이용하여 해당 roomID의 저장공간을 삭제합니다

#### ─────────────────────────────────────────────────────────────
1.  처음 구동시, zuda-backend 루트 폴더에 **fileStorage 폴더** 가 존재해야합니다
     fileStorage폴더가 존재한다면, 업로드 할때 자동으로 temp폴더와 roomID별 폴더가 생성됩니다

2.  업로드 시, **temp폴더**에 파일들이 임시 저장되며, 요청에서 @Body를 통해 들어온 roomID로 폴더가 생성됩니다

3. 생성된 roomID 폴더로 업로드 된 파일들이 이동됩니다

4. 파일당 사이즈가 100MB 초과시 **FILE_CAPACITY_EXCEEDED**에러를 반환하도록 하였습니다
    ㄴ 파일용량은 .env에 **FILE_SIZE_PER** 에서 조절할 수 있도록 하였습니다
    
5. 업로드된 파일이 존재하지 않을 시, **NULL_UPLOAD** 에러를 반환하도록 하였습니다
<br>

### 프론트에서 요청
   #### 업로드: `form-data` 옵션, 
  >**키(key)**
  >- **roomID** - 숫자
  >- **files** - 파일 배열

   #### 삭제: `url-encoded` 옵션, 
   >**키(key)**
   >- **roomID** - 숫자
   
   #### 방 파일폴더 삭제:  `url-encoded` 옵션, 
   >**키(key)**
   >- **roomID** - 숫자
   
   <br>
   
   ### 반환 될 수 있는 에러 타입
   -  **[406] FILE_UPLOAD_FAILED** : 업로드에 실패하였습니다.
   -  **[500] FILE_CAPACITY_EXCEEDED** : 업로드 할 수 있는 파일 용량을 초과하였습니다 (파일 하나당 100MB)
   -  **[404] FILE_STORAGE_NOT_FOUND** : 해당 roomID를 가진 저장 스토리지가 존재하지 않습니다.
   -  **[406] NULL_UPLOA**: 업로드된 파일이 없습니다.
<br>
────────────────────────────────────────────────
   
### **⚠️ 기능이 구현되었으나 문제가 야기 될 수 있는 세부사항은 다음과 같습니다**
   >-  **파일 용량이 검사시, multer에서 거르지 않고 `file.service`에서 거르도록 구현하였습니다**
        -  여러 파일을 업로드 했을때, 용량이 넘는 파일을 제외하고 업로드 시킬 수 있습니다 
        `(FILE_CAPACITY_EXCEEDED 에러 반환을 제거시)` 
         -  이렇게 되면 일단 파일을 받고 검사하기 때문에  파일 업로드시 서버에서 오는 응답이 늦어지는것을 발견하였습니다
         
   >- **현재,  파일 업로드 결과를 return 할 때, `파일이 업로드 되었습니다` 문자 를 반환하게 하였습니다**
        -  한글로 된 파일을 업로드 할 경우, 자동으로 다른 문자로 변경되어 다운로드시 어려움을 겪을 수 있습니다
        -  프론트에서 파일 다운로드를 위하여 반환값 으로 **파일 주소를 return** 하면 어떨가 고민하고 있습니다
        
   >- **프론트에서 deleteStorge와 deleteFile로 해당 room의 파일 저장 폴더를 직접 삭제 할 수 있게 컨트롤러 구현하였습니다.**
       - 백엔드에서 service로 불러와 사용할 때 아마도 반환을 true / false로  변경해야 할 수 있습니다 (Exception 반환 때문에)
       
   >- **현재 코드에서 폴더에 접근하기 위해서 `// (백슬래시)` 를 사용하고 있습니다**
      - 혹시나 서버가 다른 운영체제에서 구동될시 작동이 정상적으로 되지 않을 수 있습니다
      - 코드에서 옵션을 추가하여 `\` 사용하도록 할 수 있습니다

2021-05-02 09:18 UTC, SkyLightQP commented
Codefactor 해결 후 코드 리뷰 하겠습니다

2021-05-02 09:39 UTC, HARDTACK-Dev commented
> Codefactor 해결 후 코드 리뷰 하겠습니다

오류 해결 완료하였습니다 :)

2021-05-02 11:26 UTC, SkyLightQP requested changes

2021-05-02 11:26 UTC, SkyLightQP commented on src/file/file.controller.ts
> +    const result = this.fileService.moveFile(files, fileBodyDTO)
`moveFile()`는 Promise를 반환하나 이곳에는 별다른 처리가 되어있지 않습니다.
`await` 또는 promise chaning 사용

2021-05-02 11:26 UTC, SkyLightQP commented on src/file/file.controller.ts
> +    const result = this.fileService.deleteRoomStorage(roomID)
`deleteRoomStorage()`는 Promise를 반환하나 이곳에는 별다른 처리가 되어있지 않습니다.
`await` 또는 promise chaning 사용

2021-05-02 11:27 UTC, SkyLightQP commented on src/file/dto/upload-file-body.dto.ts
> +    Files?: []
camelCase 권장

2021-05-02 11:29 UTC, SkyLightQP requested changes

2021-05-02 11:29 UTC, SkyLightQP commented on src/file/file.service.ts
> +  if(!existsSync(fileStorage + backSlash + roomID))
전반적으로 코드 Indent 및 Lint style이 미적용 된거 같습니다. 확인 부탁드립니다.

2021-05-02 11:32 UTC, SkyLightQP commented on src/file/file.service.ts
> +    if(files == null)
`==` 연산자가 아닌 `===` 연산자를 사용해주세요.

2021-05-02 11:32 UTC, SkyLightQP commented on src/shared/errors/file.error.ts
> +    code: 'file-406',
에러 코드에서 `406` 을 사용한 이유가 궁금합니다.
HTTP Status Code 406과 해당 에러코드의 의도가 다른 것 같습니다.

기존 에러코드는 `{Service}-{StatusCode}` 형태를 사용하고 있습니다. **(추후 에러코드 체제 개편 예정)**

2021-05-02 11:56 UTC, HARDTACK-Dev commented on src/file/file.service.ts
> +    if(files == null)
알겠습니다!
혹시 `==` 대신 `===`연산자를 사용하는 이유가 있을까요?
`files` 가 `null`인지 그 자체의 대한  엄격한 비교를 위해서 `===` 를 사용한 것 인지, 혹은
다른 이유가 있는지 궁금합니다

2021-05-02 11:59 UTC, SkyLightQP commented on src/file/file.service.ts
> +    if(files == null)
`==` 연산자는 값만 비교하고 타입을 비교하지 않습니다.
null과 undefined 비교를 둘 다 하기 위해 `==`를 사용했다면 `files === undefined || file === null` 을 사용하는 것이 바람직하고 해당 이유가 아니라면 더욱 사용할 이유가 없습니다.

2021-05-02 12:25 UTC, HARDTACK-Dev commented on src/shared/errors/file.error.ts
> +    code: 'file-406',
처음으로 에러 코드들을 찾아다니며 검색하였을때 때`406 - Not Acceptable` 이라는 
키워드에서 `Not Acceptable`을 `허용되지 않음`으로 단편적으로 이해하여  `406` 을 사용하였습니다

 또한 모질라 HTTP 상태코드 설명에서 `정해준 규격에 따른 어떠한 콘텐츠도 찾지 않았을 때, 웹서버가 보냅니다` 라는 
 키워드로 인하여 그렇게 생각하였는데, 제가  해당 코드가 설명에서 `서버 주도 콘텐츠 협상` 과 `HTTP 헤더`와 관련하여 이용하는 것인지 대해서 제가 잘 몰라서 잘못 사용한것 같습니다
 
**지적해주셔서 감사합니다 👍**

2021-05-02 15:03 UTC, HARDTACK-Dev commented on src/file/dto/upload-file-body.dto.ts
> +    Files?: []
확인하였습니다!
`현재 해당 Files 키워드는 필요 없을거 같아 삭제 예정입니다`

2021-05-02 16:23 UTC, HARDTACK-Dev commented
Ident 와 Lint style 적용 완료

2021-05-03 02:20 UTC, SkyLightQP requested changes

2021-05-03 02:20 UTC, SkyLightQP commented on src/file/file.service.ts
> +  async moveFile(files: Express.Multer.File[], fileBody: FileBodyDTO): Promise<string> {
`file.service.ts` 전반적으로 비동기 사용이 필요없으나 `async` 키워드가 붙어 있습니다.
제거해도 될거 같습니다.

제거시 `file.controller.ts` 부분도 await 키워드를 제거해야 될 것 같습니다.

2021-05-03 02:24 UTC, SkyLightQP requested changes

2021-05-03 02:24 UTC, SkyLightQP commented on src/room/services/room.service.ts
> +  static getRoom(): string {
불필요한 함수가 구현되있는 것 같습니다.
`getRoom()` 함수가 의도하는 동작은 해당 파일에 이미 구현되있습니다.

2021-05-03 02:28 UTC, SkyLightQP requested changes

2021-05-03 02:28 UTC, SkyLightQP commented on src/file/file.controller.ts
> +  deleteFile(@Body() FileBody: FileBodyDTO): Promise<string> {
`async` 키워드를 사용하지 않으나 Promise를 반환하고 있습니다. **리턴 타입 `string` 으로 변경 필요**

2021-05-03 02:28 UTC, SkyLightQP commented on src/file/file.service.ts
> +          if (err) throw new ConflictException(FileError.FILE_UPLOAD_FAILED);
`ConflictException` 에러는 Http Status Code 409인데,
`rename()` 과정 중 오류가 발생하면 무조건 해당 로직이 실행되므로, 500 에러(Internal server error)가 적절해보입니다.

2021-05-03 02:28 UTC, SkyLightQP commented on src/file/file.service.ts
> +              if (err) throw err;
`rename()` 함수와 마찬가지로 적절한 에러 핸들링이 필요해보입니다.

2021-05-03 02:28 UTC, SkyLightQP commented on src/file/file.service.ts
> +      if (err) throw err;
`rename()` 함수와 마찬가지로 적절한 에러 핸들링이 필요해보입니다.

2021-05-03 02:28 UTC, SkyLightQP commented on src/file/file.service.ts
> +      if (err) throw err;
`rename()` 함수와 마찬가지로 적절한 에러 핸들링이 필요해보입니다.

2021-05-03 02:28 UTC, SkyLightQP commented on package.json
> +    "rxjs-compat": "^6.6.7",
기존에 `rxjs` 가 이미 있고 `rxjs-compat` 을 사용한 코드를 못 봤는데 확인 가능할까요?

2021-05-03 03:30 UTC, HARDTACK-Dev commented on package.json
> +    "rxjs-compat": "^6.6.7",
`jwt.guard.ts` 파일에 yarn 의존성이 제대로 설치되지 않아 오류가 났었습니다.
이로인해 `rxjs-compat` 을 설치하였다가 문제를 해결하여 삭제 하였는데, 제대로 삭제가 안된 것 같습니다.
 
다시 제거해서 커밋 올리겠습니다 
감사합니다!

2021-05-03 03:33 UTC, HARDTACK-Dev commented on src/file/file.service.ts
> +  async moveFile(files: Express.Multer.File[], fileBody: FileBodyDTO): Promise<string> {
확인하였습니다!

2021-05-03 03:39 UTC, HARDTACK-Dev commented on src/room/services/room.service.ts
> +  static getRoom(): string {
앗, 저 함수는 제가 구현한 기억이 없는데 어째서 추가되어있는지 모르겠습니다😅
제거하여 올리겠습니다

2021-05-03 05:24 UTC, SkyLightQP approved these changes
이상없습니다!

2021-05-03 05:28 UTC, HARDTACK-Dev commented
> 이상없습니다!

감사합니다 :D
머지해도 괜찮을까요?

2021-05-03 05:38 UTC, HARDTACK-Dev commented
머지하였습니다!

2021-05-03 05:38 UTC, merged