해당 방(roomId) 의 파일 리스트를 조회하는 기능 추가
zzuda/zuda-backend pull request #19
Opened 2021-06-21 13:32 UTC by HARDTACK-Dev

### 해당 방(room Id)의 파일 리스트를 조회하는 기능을 추가하였습니다
---
🎉 **변경/추가점**
- **`FileListReturn`** 이 `types/index.ts` 에 추가되었습니다
- Get 메소드, **`file/list`** 을 이용한 파일 리스트 조회합니다,
- Swagger에 설명이 추가되었습니다
- 요청한 Id의 방이 존재하지 않으면 NotFoundExepction을 반환합니다
- EsLint/Prettier 정렬 

※ 게스트 Id를 이용하여 구하는 방법은 필요하다, 추후에 상의를 해봐야 할 것 같습니다
감사합니다 :)

2021-06-23 05:38 UTC, SkyLightQP requested changes

2021-06-23 05:38 UTC, SkyLightQP commented on src/file/file.controller.ts
> +    @ApiNotFoundResponse()
Swagger에 `@ApiOkResponse()` 데코레이터로 200 Status Code도 같이 표현해주세요.

2021-06-23 05:38 UTC, SkyLightQP commented on src/file/file.service.ts
> +    getRoomsFile(fileBody : FileBodyDTO): FileListReturn {
함수명을 `getRoomsFile()` 보다는 `getRoomFiles()` 가 더 나을 것 같습니다.

2021-06-23 11:55 UTC, HARDTACK-Dev commented on src/file/file.service.ts
> +    getRoomsFile(fileBody : FileBodyDTO): FileListReturn {
확인하였습니다!

2021-06-26 07:18 UTC, SkyLightQP approved these changes

2021-06-26 11:10 UTC, merged